app = "resgrid2eso"
primary_region = "dfw"
kill_signal = "SIGINT"
kill_timeout = 5

[build]
  dockerfile = "Dockerfile"

[env]
  # Log level and other non-sensitive configs can go here
  # Sensitive configs should be set with fly secrets

[processes]
  app = "node listener.js"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]